# Generated by Django 6.0.5 on 2026-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Paciente'), ('doctor', 'Doctor'), ('admin', 'Administrador')], default='patient', max_length=20),
        ),
    ]
