# Generated by Django 6.0.5 on 2026-07-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('patient', 'Paciente'), ('receptionist', 'Recepcionista')], default='patient', max_length=20),
        ),
    ]
