# Generated by Django 6.0.5 on 2026-08-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('patient', 'Paciente'), ('receptionist', 'Recepcionista'), ('esthetician', 'Esteticista')], default='patient', max_length=20),
        ),
    ]
