# Generated by Django 6.0.5 on 2026-07-21 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial Médico', 'verbose_name_plural': 'Historiales Médicos'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='consultation',
            field=models.CharField(choices=[('first', 'Primera consulta'), ('control', 'Control'), ('emergency', 'Urgencia')], default='first', max_length=20, verbose_name='Consulta'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(default='', verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
    ]
