"""
Django settings for gutty_health_system project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# 🔐 SECURITY
# =========================

SECRET_KEY = 'django-insecure-f3ybtvtgl*+i9qqybu7d1_g34y!8ncz6s_k(*)-7p_8&*pyzue'

DEBUG = True


ALLOWED_HOSTS = [

    "localhost",

    "127.0.0.1",

]




# =========================
# 📦 APPS
# =========================

INSTALLED_APPS = [


    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',



    # Proyecto

    'users',

    'appointments',

    'medical_records',

    'documents',

    'billing',

    'dashboard',

    'pqr',



    # Terceros

    'corsheaders',

    'rest_framework',

    'rest_framework_simplejwt',

]


AUTH_USER_MODEL = 'users.User'






# =========================
# 🔧 MIDDLEWARE
# =========================

MIDDLEWARE = [


    'corsheaders.middleware.CorsMiddleware',


    'django.middleware.security.SecurityMiddleware',


    'django.contrib.sessions.middleware.SessionMiddleware',


    'django.middleware.common.CommonMiddleware',


    'django.middleware.csrf.CsrfViewMiddleware',


    'django.contrib.auth.middleware.AuthenticationMiddleware',


    'django.contrib.messages.middleware.MessageMiddleware',


    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]





ROOT_URLCONF = 'gutty_health_system.urls'






# =========================
# 🎨 TEMPLATES
# =========================

TEMPLATES = [


    {

        'BACKEND':
        'django.template.backends.django.DjangoTemplates',


        'DIRS': [],


        'APP_DIRS': True,


        'OPTIONS': {


            'context_processors': [


                'django.template.context_processors.request',


                'django.contrib.auth.context_processors.auth',


                'django.contrib.messages.context_processors.messages',


            ],


        },


    },


]






WSGI_APPLICATION = 'gutty_health_system.wsgi.application'







# =========================
# 🗄️ DATABASE
# =========================

DATABASES = {


    'default': {


        'ENGINE':
        'django.db.backends.sqlite3',


        'NAME':
        BASE_DIR / 'db.sqlite3',


    }


}





# =========================
# 🔒 PASSWORDS
# =========================

AUTH_PASSWORD_VALIDATORS = [


    {

        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'

    },


    {

        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator'

    },


    {

        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator'

    },


    {

        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator'

    },


]






# =========================
# 🌎 IDIOMA
# =========================

LANGUAGE_CODE = 'es-co'


TIME_ZONE = 'America/Bogota'


USE_I18N = True


USE_TZ = True







# =========================
# 📁 STATIC
# =========================

STATIC_URL = '/static/'


STATIC_ROOT = BASE_DIR / 'staticfiles'







# =========================
# 📂 MEDIA DOCUMENTOS
# =========================

MEDIA_URL = '/media/'


MEDIA_ROOT = BASE_DIR / 'media'







# =========================
# 📤 UPLOAD ARCHIVOS
# =========================

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024






DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







# =========================
# 🌐 CORS ANGULAR
# =========================

CORS_ALLOWED_ORIGINS = [


    "http://localhost:4200",


    "http://127.0.0.1:4200",


]


CORS_ALLOW_CREDENTIALS = True






# =========================
# 🔥 CSRF
# =========================

CSRF_TRUSTED_ORIGINS = [


    "http://localhost:4200",


    "http://127.0.0.1:4200",


]






# =========================
# 🔌 DJANGO REST FRAMEWORK
# =========================

REST_FRAMEWORK = {


    'DEFAULT_AUTHENTICATION_CLASSES': (


        'rest_framework_simplejwt.authentication.JWTAuthentication',


    ),



    'DEFAULT_PERMISSION_CLASSES': (


        'rest_framework.permissions.AllowAny',


    ),



    'DEFAULT_RENDERER_CLASSES': (


        'rest_framework.renderers.JSONRenderer',


    ),



    'DEFAULT_PARSER_CLASSES': (


        'rest_framework.parsers.JSONParser',


        'rest_framework.parsers.MultiPartParser',


        'rest_framework.parsers.FormParser',


    ),


}





# =========================
# 🔑 JWT
# =========================

SIMPLE_JWT = {


    'ACCESS_TOKEN_LIFETIME':

    timedelta(hours=24),



    'REFRESH_TOKEN_LIFETIME':

    timedelta(days=7),



    'AUTH_HEADER_TYPES':

    ('Bearer',),



    'AUTH_HEADER_NAME':

    'HTTP_AUTHORIZATION',


}

# =========================
# 📧 CONFIGURACIÓN EMAIL
# =========================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'jimenezandru91@gmail.com'  # Cambia por tu correo real

# Contraseña de aplicación de Gmail (16 caracteres, sin espacios)
EMAIL_HOST_PASSWORD = 'nwusfguezlqvowxs'  # Cambia por tu contraseña de aplicación

DEFAULT_FROM_EMAIL = f'Instituto Médico Asdrúbal Gutty <{EMAIL_HOST_USER}>'

SERVER_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_TIMEOUT = 30
