# Generated by Django 6.0.5 on 2026-07-29 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('exam', 'Examen'), ('photo', 'Fotografía'), ('image', 'Imagen'), ('prescription', 'Fórmula médica'), ('consent', 'Consentimiento informado'), ('order', 'Orden médica'), ('other', 'Otro')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento médico',
                'verbose_name_plural': 'Documentos médicos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
