# Generated by Django 6.0.5 on 2026-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('first', 'Primera cita dermatología'), ('control', 'Control dermatológico'), ('followup', 'Seguimiento tratamiento'), ('delivery', 'Entrega medicamentos'), ('spa', 'Spa Natural Gutty'), ('cosmetic', 'Limpieza facial')], max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reprogramada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
