# Generated by Django 6.0.5 on 2026-08-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_options_and_more'),
    ]

    operations = [
    ]
