# Generated by Django 6.0.5 on 2026-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqr_type', models.CharField(choices=[('complaint', 'Queja'), ('claim', 'Reclamo'), ('suggestion', 'Sugerencia'), ('praise', 'Felicitación')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
