# Generated by Django 6.0.5 on 2026-07-31 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqr',
            options={'ordering': ['-created_at'], 'verbose_name': 'PQR', 'verbose_name_plural': 'PQR'},
        ),
        migrations.AddField(
            model_name='pqr',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pqr',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_pqrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pqr',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pqr',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En proceso'), ('closed', 'Cerrada')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='pqr',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pqr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='pqr_type',
            field=models.CharField(choices=[('petition', 'Petición'), ('complaint', 'Queja'), ('claim', 'Reclamo'), ('suggestion', 'Sugerencia'), ('praise', 'Felicitación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pqr',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to=settings.AUTH_USER_MODEL),
        ),
    ]
