# Generated by Django 6.0.5 on 2026-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0003_alter_pqr_options_pqr_responded_at_pqr_responded_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqr',
            options={'ordering': ['-created_at'], 'verbose_name': 'PQR', 'verbose_name_plural': 'PQRs'},
        ),
        migrations.AlterField(
            model_name='pqr',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
